apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: tf-text-clf-serve-dc
  annotations:
    scenarios.ai.sap.com/description: "Tensorlfow text classification"
    scenarios.ai.sap.com/name: "movie-review-clf-dc"
    executables.ai.sap.com/description: "Tensorlfow GPU Serving executable"
    executables.ai.sap.com/name: "serve-exectuable"
  labels:
    scenarios.ai.sap.com/id: "tf-text-clf-dc"
    ai.sap.com/version: "2.0.0"
spec:
  inputs:
    artifacts:
    - name: modelArtifact
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: starter #infer.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: credsdicksonc
        containers:
        - name: kfserving-container
          image: "docker.io/dicksonc/movie-review-clf-serve:0.0.2"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.modelArtifact}}"
